#!/bin/bash
#
# Copyright (c) 2010-2014, Benjamin C. Meyer <ben@meyerhome.net>
# Copyright (c) 2013, Phil Black-Knight <pblack88@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
# 3. Neither the name of the project nor the
#    names of its contributors may be used to endorse or promote products
#    derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ''AS IS'' AND ANY
# EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

function test_file {
    file="${1}"
    if [ ! -f "${file}" ] ; then
        return
    fi
    if grep 'Copyright ' "${file}" | grep -v grep >/dev/null
    then
        year=`date +%Y`
        cr_holder=`git config --get hooks.copyrightholder`
        if [ -n "${cr_holder}" ]
        then
            grep 'Copyright ' "${file}" | grep "${year}" | grep "${cr_holder}" >/dev/null
            if [ $? -ne 0 ] ; then
                echo "Error: $file seems to be missing a copyright string for ${cr_holder} with the year $year in it.";
                exit 1
            fi
        else
            grep 'Copyright ' "${file}" | grep "${year}" >/dev/null
            if [ $? -ne 0 ] ; then
                echo "Error: $file seems to be missing a copyright string with the year $year in it.";
                exit 1
            fi
        fi
    fi
}

case "${1}" in
    --about )
        cat << EOF
Check that the files have a copyright with the current year.  If the git config key
"hooks.copyrightholder" is set, the script will verify that in addition to the
current year, a copyright notice exists for person/entity listed in "hooks.copyrightholder"
EOF
        ;;
    * )
        for file in `git diff-index --cached --name-only HEAD` ; do
            test_file "${file}"
        done
        ;;
esac
